[[main]]
  name = "ğŸ’¡ blog"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "ğŸ•¹ï¸ projets"
  pageRef = "projets"
  weight = 20

[[main]]
  name = "ğŸ“ cv"
  pageRef = "cv"
  weight = 30

# [[main]]
#   name = "GitHub"
#   url = "https://github.com/nabilainas"
#   weight = 30
#   [main.params]
#     icon = "github"
#     showName = false
#     target = "_blank"

[[main]]
  identifier = "search"
  weight = 99
[main.params]
  action = "search"
  icon = "search"


[[footer]]
  pageRef = "privacy"